name: indi_tool
description: "INDI Diagnostics Tool."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  # Flutter SDK
  flutter:
    sdk: flutter

  # Google Fonts
  google_fonts: ^6.2.1

  # Riverpod state management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Drift Database w/ SQLite
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.24

  # RxDart for reactive programming
  rxdart: ^0.27.7

  # Compression support
  es_compression: ^2.0.12

  # Path provider for common file paths
  path_provider: ^2.1.3

  # Path manipulation
  path: ^1.9.0

  # Manages the app's window
  window_manager: ^0.3.9

  # For generating UUIDs
  uuid: ^4.4.0

  # HTTP requests
  http: ^1.2.1

  # For interacting with canvas
  touchable: ^1.0.2

  # For creating a tree view
  flutter_fancy_tree_view: ^1.6.0

  # Internationalization
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Default Lints
  flutter_lints: ^4.0.0

  # Riverpod Generator
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

  # Build Runner for code generation
  build_runner: ^2.4.11

  # Custom Linting
  custom_lint: ^0.6.4
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true

  assets:
    - assets/libs/zstd/zstd-1_5_4-win64.dll
    - assets/libs/zstd/zstd-1_5_4-mac64.dylib
    - assets/libs/zstd/zstd-1_5_4-linux64.so
