name: indi_tool
description: "INDI Diagnostics Tool."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1

  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  window_manager: ^0.3.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  build_runner: ^2.4.11
  custom_lint: ^0.6.4

flutter:
  uses-material-design: true
